[build]
	command = "npm run build"
	publish = "build"

[[redirects]]
from = "https://brainwaves-ai-newsletter.netlify.app"
to = "https://ia.minimo.io"
status = 301
force = true

[[redirects]]
from = "https://brainwaves-ai-newsletter.netlify.app/*"
to = "https://ia.minimo.io/:splat"
status = 301
force = true